// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flavour-item-master/Current.tsx": () => import("../components/mockups/flavour-item-master/Current.tsx"),
  "./components/mockups/flavour-item-master/VariantA.tsx": () => import("../components/mockups/flavour-item-master/VariantA.tsx"),
  "./components/mockups/flavour-item-master/VariantB.tsx": () => import("../components/mockups/flavour-item-master/VariantB.tsx")
};
